db:
  driver: com.mysql.cj.jdbc.Driver
  password: admin
  url: jdbc:mysql://localhost:3306/covid?createDatabaseIfNotExist=true
  username: root
entitymanager:
  packagesToScan: com
hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect
  format_sql: false
  hbm2ddl:
    auto: update
  show_sql: true
  
logging:
  file:
    name: log/mylog.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
server:
  port: 8091
spring:
  application:
    name: COVID19-SERVICE
  
  
management:
  endpoints:
    web: 
      exposure:
        include: "*"  # This exposes all endpoints, you can customize which ones to expose
      base-path: /actuator 
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true 
      

 
                  
